### ISSUE TITLE
Update for JSP 2.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hazendaz/htmlcompressor#97]
```
The attached patch will update the compressor library for JSP 2.2, Guava, and 
Closure Compiler libraries.


```

Original issue reported on code.google.com by `johnye...@gmail.com` on 5 Jul 2014 at 1:08

Attachments:
- [HtmlCompressorPatch.patch](https://storage.googleapis.com/google-code-attachments/htmlcompressor/issue-97/comment-0/HtmlCompressorPatch.patch)

**Comment by hazendaz** [comment]
done a long time back.  closing.
